# -*- coding: utf-8 -*-
"""
/***************************************************************************
 bpla_plugin_flights
                                 A QGIS plugin
 Selecting and deleting odds and ends of flights.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-13
        copyright            : (C) 2021 by SibGis
        email                : sibgis@qgis.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load bpla_plugin_flights class from file bpla_plugin_flights.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .bpla_plugin_flights import bpla_plugin_flights
    return bpla_plugin_flights(iface)
